version: '3.8'

services:
  local_db:
    image: postgres:15-alpine
    container_name: nawaloka_pg_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localpassword
      POSTGRES_DB: medicore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: