"""
SQL Validator Module.

Acts as the Safety Layer for the NL2SQL engine. 
Blocks destructive commands, enforces SELECT-only queries, 
and performs basic syntax checks.
"""

import re

class SQLValidator:
    """Validator class to ensure generated SQL is safe to execute."""

    def __init__(self):
        """Initializes the validator with a list of forbidden SQL operations."""
        self.forbidden_keywords = [
            "DROP", "DELETE", "TRUNCATE", "UPDATE", "INSERT", "ALTER", 
            "GRANT", "REVOKE", "COMMIT", "ROLLBACK"
        ]

    def validate_query(self, query: str) -> dict:
        """
        Validates the SQL query for destructive commands and basic syntax.
        
        Args:
            query (str): The SQL query generated by the LLM.
            
        Returns:
            dict: A dictionary containing 'is_valid' (bool) and 'message' (str).
        """
        # Clean the query
        query = query.strip()
        upper_query = query.upper()

        # 1. Catch completely empty queries
        if not query:
            return {"is_valid": False, "message": "Query is empty."}

        # 2. Block destructive commands
        for keyword in self.forbidden_keywords:
            # Use regex to match exact words (prevents blocking a column named 'drop_time')
            if re.search(rf'\b{keyword}\b', upper_query):
                return {
                    "is_valid": False, 
                    "message": f"Security Violation: Destructive command '{keyword}' is strictly prohibited."
                }

        # 3. Enforce SELECT-only (or WITH for CTEs)
        if not upper_query.startswith(("SELECT", "WITH")):
            return {
                "is_valid": False, 
                "message": "Syntax Violation: Query must begin with SELECT or WITH."
            }

        # 4. Basic Syntax Error Catch: Unbalanced Parentheses
        if query.count("(") != query.count(")"):
            return {
                "is_valid": False, 
                "message": "Syntax Error: Unbalanced parentheses detected in the query."
            }

        # If it passes all checks
        return {"is_valid": True, "message": "Query is safe and valid."}

# Quick test block
if __name__ == "__main__":
    print("--- Testing SQL Validator ---")
    validator = SQLValidator()
    
    test_queries = [
        "SELECT * FROM patients WHERE active = true;",
        "DROP TABLE patients;",
        "UPDATE doctors SET active = false;",
        "SELECT COUNT(*) FROM bookings WHERE (status = 'PENDING';"
    ]
    
    for q in test_queries:
        result = validator.validate_query(q)
        status = "✅ PASS" if result["is_valid"] else "❌ FAIL"
        print(f"\nQuery: {q}")
        print(f"Result: {status} -> {result['message']}")